name: "Python CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    uses: darbiadev/.github/.github/workflows/generic-precommit.yaml@4aa7c64159244d12bf9a39d42da89e80004d4af6

  lint:
    needs: pre-commit
    uses: darbiadev/.github/.github/workflows/python-lint.yaml@4aa7c64159244d12bf9a39d42da89e80004d4af6

  test:
    needs: lint
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]

    uses: darbiadev/.github/.github/workflows/python-test.yaml@4aa7c64159244d12bf9a39d42da89e80004d4af6
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
